type Query {
    products(
        product_name: String = "",
        category_id: ID = 0,
        product_id: ID = 0,
        page: Int = 1,
        limit: Int = 5
    ): [Product!]!,

    categories(
        category_id: ID = 0,
        page: Int = 1,
        limit: Int = 5
    ): [Category!]!
}

type Product {
    category_id: ID!,
    product_id: ID!,
    product_name: String!,
    price: Int,
    short_desc: String!,
    long_desc: String!
}

type Category {
    category_id: ID!,
    category_name: String!    
}