scalar Any
scalar Password
scalar Contact
scalar Email

type Mutation {
    register(
        username: String!,
        password: Password!,
        contact: Contact!,
        email: String!,
    ): Any,

    login(
        username: String!,
        password: String!
    ): Any
}

type User {
    user_id: ID!,
    username: String!,
    password: Password!,
    contact: Contact!,
    email: String!,
}

type Response {
    status: Int,
    message: Any
}